# Generated by Django 4.2.1 on 2023-05-13 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('item_genero', models.CharField(max_length=20, verbose_name='Item Genero')),
                ('estado', models.BooleanField(default=True, verbose_name='Genero Activo/Inactivo')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
                'ordering': ['item_genero'],
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_localidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_localidad', models.CharField(max_length=50, verbose_name='Nombre Localidad')),
                ('estado', models.BooleanField(default=True, verbose_name='Localidad Activo/Inactivo')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidads',
                'ordering': ['nombre_localidad'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_documento', models.CharField(max_length=50, verbose_name='Nombre Tipo documnento')),
                ('estado', models.BooleanField(default=True, verbose_name='Tipo Documento Activo/Inactivo')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'TipoDocumento',
                'verbose_name_plural': 'TipoDocumento',
                'ordering': ['nombre_tipo_documento'],
            },
        ),
        migrations.CreateModel(
            name='Votante',
            fields=[
                ('no_documento_votante', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Numero documento')),
                ('nombres_votante', models.CharField(verbose_name='Nombres')),
                ('apellidos_votante', models.CharField(verbose_name='Apellidos')),
                ('estado', models.BooleanField(default=True, verbose_name='Votante Activo/Inactivo')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('id_genero_votante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.genero')),
                ('id_localidad_votante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.localidad')),
                ('id_tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.tipodocumento')),
            ],
            options={
                'verbose_name': 'Votante',
                'verbose_name_plural': 'Votantes',
                'ordering': ['nombres_votante'],
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('no_documento_candidato', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Numero documento')),
                ('nombres_candidato', models.CharField(verbose_name='Nombres')),
                ('apellidos_candidato', models.CharField(verbose_name='Apellidos')),
                ('partido_candidato', models.CharField(verbose_name='Partido candidato')),
                ('estado', models.BooleanField(default=True, verbose_name='Votante Activo/Inactivo')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('id_genero_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.genero')),
                ('id_localidad_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.localidad')),
                ('id_tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.tipodocumento')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['nombres_candidato'],
            },
        ),
    ]
