# Generated by Django 4.2.1 on 2023-05-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id_voto', models.AutoField(primary_key=True, serialize=False)),
                ('no_documento_votante', models.CharField(max_length=50, verbose_name='No documento votante')),
                ('no_documento_candidato', models.CharField(max_length=50, verbose_name='No documento votante')),
                ('estado', models.BooleanField(default=True, verbose_name='Localidad Activo/Inactivo')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidads',
                'ordering': ['id_voto'],
            },
        ),
    ]
